[build-system]
requires = ["setuptools>=46.4.0", "setuptools_scm[toml]>=6.2.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "icd/_version.py"
local_scheme = "no-local-version"
