name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install deps & package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[test]
      - name: Run tests
        run: |
          export ICD_API_ID="${{ secrets.ICD_API_ID }}"
          export ICD_API_SECRET="${{ secrets.ICD_API_SECRET }}"
          coverage run --omit=tests/*,*/_*.py -m pytest ./tests -vv
          coverage xml
      - name: Upload to codecov
        uses: codecov/codecov-action@v2
