name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ICD_API_ID: ${{ secrets.ICD_API_ID }}
  ICD_API_SECRET: ${{ secrets.ICD_API_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Check environment variables
        run: |
          echo $ICD_API_ID
          echo: $ICD_API_SECRET
      - name: Install deps & package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[test]
      - name: Run tests
        run: |
          coverage run --omit=tests/*,*/_*.py -m pytest ./tests -vv
          coverage xml
      - name: Upload to codecov
        uses: codecov/codecov-action@v2
